"""Aggregate results/*.json -> docs/REPORT.md (all evidence tables). No numbers are fabricated: missing runs show '—'."""
import glob
import os

from .utils.misc import load_json, md_table

ABL = [("cam", "cam"), ("cam+L", "cam_lidar"), ("cam+L+R", "cam_lidar_radar"), ("cam+L+R, no deform-attn", "no_deform"),
       ("cam+L+R, fixed loss weights", "fixed_weights")]
ROB = [("radar on", "cam_lidar_radar"), ("radar dropped 50%", "cam_lidar_radar_rdrop50"), ("radar dropped 100%", "cam_lidar_radar_rdrop100")]
DOM = [("all mini_val", "cam_lidar_radar"), ("rain", "cam_lidar_radar_rain"), ("night", "cam_lidar_radar_night"), ("clear/day", "cam_lidar_radar_clear_day")]


def f(m, k, nd=3):
    v = m.get(k) if m else None
    return "—" if v is None else f"{v:.{nd}f}"


def main():
    R = {os.path.basename(p)[:-5]: load_json(p) for p in glob.glob("results/*.json")}
    rows = lambda spec: [[lbl, f(R.get(k), "mAP"), f(R.get(k), "NDS"), f(R.get(k), "seg_mIoU"), f(R.get(k), "occ_mIoU")] for lbl, k in spec]
    hdr = ["Config", "mAP", "NDS", "BEV-seg mIoU", "Occ mIoU"]
    md = ["# Results (auto-generated by `python -m obf.report`)", "",
          "## Modality / architecture ablation (nuScenes-mini val)", md_table(rows(ABL), hdr), "",
          "## Radar-dropout robustness (test-time)", md_table(rows(ROB), hdr), "",
          "## Domain shift: adverse-weather subsets", md_table(rows(DOM), hdr), ""]
    g = R.get("goose_transfer", {}); gz = R.get("goose_zero_shot", {})
    md += ["## Off-road transfer (GOOSE)", md_table([["nuScenes-trained, zero-shot (drivable vs rest)", f(gz, "seg_mIoU")],
                                                    ["fine-tuned on GOOSE (8 classes)", f(g, "seg_mIoU")],
                                                    ["source→target drop (drivable IoU)", f(R.get("goose_drop"), "drivable_drop")]],
                                                   ["Setting", "mIoU"]), ""]
    if os.path.exists("results/latency_l4.md"):
        md += ["## Latency (L4, batch 1)", open("results/latency_l4.md").read(), ""]
    v = R.get("vla_safety", {})
    md += ["## VLA task grounding — 50-frame safety eval", md_table([
        ["stop recall (pedestrian < 5 m in path)", f(v, "stop_recall")], ["stop∪wait recall", f(v, "stop_or_wait_recall")],
        ["false-stop rate (no hazard)", f(v, "false_stop_rate")], ["JSON parse success", f(v, "parse_rate")]], ["Metric", "Value"]), ""]
    os.makedirs("docs", exist_ok=True)
    open("docs/REPORT.md", "w").write("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
